language: cpp

env:
  global:
  - MAKEFLAGS=-j1

matrix:
  fast_finish: true
  include:
  - compiler: ": Win32"
    env:
    - APT_REPOS=""
    - APT_PACKAGES="p7zip binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686 wine1.4-i386:i386"
    - MINGW_PREFIX=i686-w64-mingw32
    - DBGHELP_URL=https://www.googledrive.com/host/0B1mEXoWzDm1McE81WFBKTzd5Z3M
    - WINE_PROGRAM=/usr/bin/wine
  - compiler: ": Win64"
    env:
    - APT_REPOS="ppa:ubuntu-wine/ppa"
    - APT_PACKAGES="p7zip binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 wine1.6-amd64"
    - MINGW_PREFIX=x86_64-w64-mingw32
    - DBGHELP_URL=https://www.googledrive.com/host/0B1mEXoWzDm1MaGlUZ0syNEduTGs
    - WINE_PROGRAM=/usr/bin/wine64

before_install:
- for APT_REPO in $APT_REPOS; do sudo add-apt-repository -y $APT_REPO; done
- sudo apt-get update -qq
- sudo apt-get install -qq -y --no-install-recommends $APT_PACKAGES

script:
- |
    echo "set (CMAKE_SYSTEM_NAME Windows)" > Toolchain.cmake
    echo "set (CMAKE_C_COMPILER $MINGW_PREFIX-gcc)" >> Toolchain.cmake
    echo "set (CMAKE_CXX_COMPILER $MINGW_PREFIX-g++)" >> Toolchain.cmake
    echo "set (CMAKE_RC_COMPILER $MINGW_PREFIX-windres)" >> Toolchain.cmake
    echo "set (CMAKE_FIND_ROOT_PATH /usr/$MINGW_PREFIX)" >> Toolchain.cmake
    echo "set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)" >> Toolchain.cmake
    echo "set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)" >> Toolchain.cmake
    echo "set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> Toolchain.cmake
- wget -q -O dbghelp.7z "$DBGHELP_URL"
- 7zr x -othirdparty/dbghelp/ dbghelp.7z
- cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=Toolchain.cmake -DWINDBG_DIR=thirdparty/dbghelp -DWINE_PROGRAM=$WINE_PROGRAM
- make -C build all test package

deploy:
  provider: releases
  api_key:
    secure: frTz8L+ex+foqv1fpVJX9guW/YHftxhjJ3SKwcfLmIW/NP77FVLgF8PgyLyPVbRkUOoSZpNYGQcWEpOF3bEK5HbeQScuV75TgSO2n2Ie4UqMO7+4G3bY5+Ni/SvfA/qt7krZQeNc0wCtPX+QjD4HLmSXfnie6PMZw/q5pkjN9fI=
  file_glob: true
  file: build/drmingw-*.zip
  on:
    repo: jrfonseca/drmingw
    tags: true
    all_branches: true
